# -*- coding: utf-8 -*-
"""_Skripsi_Vtuber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHsE038_kVhl_6S2YqCBuRW2LxCJuOEd
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os

# Path folder Drive kampus yang sudah kamu buat
path_folder = "/content/drive/MyDrive/_Skripsi_Vtuber/"

file_master = os.path.join(path_folder, "master_data_vtuber.xlsx")
file_latih = os.path.join(path_folder, "data_latih_1000_labeled.xlsx")

# Membaca data ke sistem Colab
df_master = pd.read_excel(file_master)
df_latih = pd.read_excel(file_latih)

print("=== LAPORAN KESIAPAN DATA SKRIPSI ===")
print(f"-> Data Master (Populasi) : {df_master.shape[0]} baris berhasil terbaca.")
print(f"-> Data Latih (Sampel)    : {df_latih.shape[0]} baris berhasil terbaca.")
print("=====================================")

import re
import string
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

print("Memulai inisialisasi mesin preprocessing...")

# 1. Mengaktifkan Mesin Stemmer Sastrawi untuk Bahasa Indonesia
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# 2. Kamus Normalisasi Slang & Jargon VTuber Indonesia
kamus_slang = {
    "ga": "tidak", "gak": "tidak", "gk": "tidak", "ndak": "tidak", "ngga": "tidak",
    "udh": "sudah", "dlu": "dulu", "jg": "juga", "dgn": "dengan",
    "kalo": "kalau", "bgt": "banget", "bangett": "banget", "bgtu": "begitu",
    "krn": "karena", "karna": "karena", "gw": "saya", "gua": "saya", "lu": "kamu",
    "stream": "siaran", "streaming": "siaran", "live": "siaran", "riging": "rigging",
    "wkwk": "tertawa", "wkwkwk": "tertawa", "awokwok": "tertawa", "ngakak": "tawa"
}

def normalisasi_teks(teks):
    words = teks.split()
    normalized_words = [kamus_slang.get(word, word) for word in words]
    return " ".join(normalized_words)

# 3. Fungsi Utama Pembersihan Teks (Menggabungkan Seluruh Prosedur Bab III)
def eksekusi_preprocessing(teks):
    if not isinstance(teks, str):
        return ""

    # a. Case Folding (Mengubah semua huruf menjadi kecil)
    teks = teks.lower()

    # b. Cleansing (Menghapus Mention, URL, Angka, dan Tanda Baca)
    teks = re.sub(r'@[A-Za-z0-9_\-]+', '', teks)  # Hapus @username
    teks = re.sub(r'http\S+|www\S+|https\S+', '', teks)  # Hapus Link URL
    teks = re.sub(r'\d+', '', teks)  # Hapus Angka
    teks = teks.translate(str.maketrans('', '', string.punctuation))  # Hapus Tanda Baca
    teks = re.sub(r'\s+', ' ', teks).strip()  # Hapus Spasi Berlebih

    # c. Normalisasi Slang
    teks = normalisasi_teks(teks)

    # d. Stemming Bahasa Indonesia (Mengubah ke Kata Dasar via Sastrawi)
    # DISINI PERBAIKANNYA: pakai .stem()
    teks = stemmer.stem(teks)

    return teks

print("Mesin siap! Melangsungkan preprocessing pada Data Latih (1.000 baris)...")
# Menjalankan fungsi pembersihan ke data 1.000 baris
df_latih['Cleaned Text'] = df_latih['Chat Text'].apply(eksekusi_preprocessing)

print("\n=== HASIL PERBANDINGAN PREPROCESSING ===")
print(df_latih[['Chat Text', 'Cleaned Text']].head(5))
print("=========================================")

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("Memulai proses Train-Test Split...")
df_latih['Cleaned Text'] = df_latih['Cleaned Text'].fillna('')

X = df_latih['Cleaned Text']
y = df_latih['Label Sentimen']

# Split data awal
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("Melangsungkan Teknik Oversampling manual pada Data Latih...")
# Menggabungkan kembali data train untuk proses balancing
df_train_temp = pd.DataFrame({'Text': X_train, 'Label': y_train})
df_positif = df_train_temp[df_train_temp['Label'] == 'Positif']
df_negatif = df_train_temp[df_train_temp['Label'] == 'Negatif']

# Mendutplikasi data negatif agar jumlahnya seimbang dengan data positif
df_negatif_oversampled = df_negatif.sample(len(df_positif), replace=True, random_state=42)
df_train_balanced = pd.concat([df_positif, df_negatif_oversampled])

# Memisahkan kembali setelah seimbang
X_train_balanced = df_train_balanced['Text']
y_train_balanced = df_train_balanced['Label']

print(f"-> Ukuran data latih baru setelah diseimbangkan: {len(X_train_balanced)} baris.")

# Ekstraksi Fitur TF-IDF
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train_balanced)
X_test_tfidf = vectorizer.transform(X_test)

# Melatih ulang model Naïve Bayes
model_nb_balanced = MultinomialNB()
model_nb_balanced.fit(X_train_tfidf, y_train_balanced)

# Pengujian ulang
y_pred = model_nb_balanced.predict(X_test_tfidf)

print("\n" + "="*40)
print("   HASIL EVALUASI MODEL BARU (BALANCED)   ")
print("="*40)
print(f"Skor Akurasi Baru : {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\nClassification Report Perbaikan:")
print(classification_report(y_test, y_pred))
print("="*40)

# Visualisasi Confusion Matrix Baru
cm = confusion_matrix(y_test, y_pred, labels=['Positif', 'Negatif'])
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Positif', 'Negatif'], yticklabels=['Positif', 'Negatif'])
plt.title('Confusion Matrix Terkoreksi - Klasifikasi VTuber')
plt.ylabel('Data Asli (Actual)')
plt.xlabel('Hasil Prediksi Model (Predicted)')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

print("Melatih model menggunakan Complement Naïve Bayes (CNB) khusus Imbalanced Text...")

# 1. Menggunakan data asli tanpa oversampling paksa
X = df_latih['Cleaned Text']
y = df_latih['Label Sentimen']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 2. Ekstraksi Fitur TF-IDF
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# 3. Mengaktifkan ComplementNB
model_cnb = ComplementNB()
model_cnb.fit(X_train_tfidf, y_train)

# 4. Prediksi
y_pred_cnb = model_cnb.predict(X_test_tfidf)

print("\n" + "="*40)
print("     HASIL EVALUASI MODEL DENGAN CNB      ")
print("="*40)
print(f"Skor Akurasi CNB : {accuracy_score(y_test, y_pred_cnb) * 100:.2f}%")
print("\nClassification Report CNB:")
print(classification_report(y_test, y_pred_cnb))
print("="*40)

# 5. Visualisasi Confusion Matrix CNB
cm_cnb = confusion_matrix(y_test, y_pred_cnb, labels=['Positif', 'Negatif'])
plt.figure(figsize=(6,4))
sns.heatmap(cm_cnb, annot=True, fmt='d', cmap='Blues', xticklabels=['Positif', 'Negatif'], yticklabels=['Positif', 'Negatif'])
plt.title('Confusion Matrix - Complement Naïve Bayes')
plt.ylabel('Data Asli (Actual)')
plt.xlabel('Hasil Prediksi Model (Predicted)')
plt.show()

import re
import string
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Pastikan mesin stemmer utama aktif
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# BUKU INGATAN: Memori khusus biar Sastrawi gak mikir dua kali untuk kata yang sama
stem_cache = {}

def eksekusi_preprocessing_cepat(teks):
    if not isinstance(teks, str):
        return ""

    # a. Case Folding
    teks = teks.lower()

    # b. Cleansing
    teks = re.sub(r'@[A-Za-z0-9_\-]+', '', teks)
    teks = re.sub(r'http\S+|www\S+|https\S+', '', teks)
    teks = re.sub(r'\d+', '', teks)
    teks = teks.translate(str.maketrans('', '', string.punctuation))
    teks = re.sub(r'\s+', ' ', teks).strip()

    # c. Normalisasi Slang
    teks = normalisasi_teks(teks)

    # d. Fast Stemming Menggunakan Cache Kata (Rahasianya di sini!)
    words = teks.split()
    stemmed_words = []
    for word in words:
        if word not in stem_cache:
            # Cuma manggil rumus Sastrawi kalau katanya bener-bener baru belum pernah ketemu
            stem_cache[word] = stemmer.stem(word)
        stemmed_words.append(stem_cache[word])

    return " ".join(stemmed_words)

# --- EKSEKUSI ULANG DENGAN KECEPATAN TINGGI ---
print("1. Memulai pembersihan KILAT Data Master (62.504 baris) dengan sistem Cache...")
df_master['Cleaned Text'] = df_master['Chat Text'].apply(eksekusi_preprocessing_cepat)
print("-> Pembersihan kilat data master selesai dalam hitungan menit!")

# 2. Mengubah teks bersih data master menjadi bentuk angka TF-IDF
X_master_tfidf = vectorizer.transform(df_master['Cleaned Text'].fillna(''))

# 3. Prediksi Sentimen Massal menggunakan model CNB teruji
print("\n2. Melangsungkan prediksi sentimen massal pada seluruh data master...")
df_master['Prediksi Sentimen'] = model_cnb.predict(X_master_tfidf)

print("\n=== DISTRIBUSI SENTIMEN DATA MASTER ===")
print(df_master['Prediksi Sentimen'].value_counts())
print("=======================================")

# Commented out IPython magic to ensure Python compatibility.
# %whos

import os
import glob
import pandas as pd
import google.colab.drive as drive

# 1. Mount Drive jika belum
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

FOLDER_PATH = '/content/drive/MyDrive/_Skripsi_Vtuber'

print("=== CEK DIREKTORI & FILE DRIVE ===\n")

# 2. Cek apakah folder skripsi ada
if not os.path.exists(FOLDER_PATH):
    print(f"❌ Folder tidak ditemukan: {FOLDER_PATH}")
    print("Folder yang ada di MyDrive kamu saat ini:")
    for item in os.listdir('/content/drive/MyDrive'):
        if not item.startswith('.'):
            print(f"  - {item}")
else:
    print(f"✅ Folder ditemukan: {FOLDER_PATH}\n")
    print("Daftar semua file di dalam folder:")
    files = [f for f in os.listdir(FOLDER_PATH) if not f.startswith('.')]
    for f in files:
        print(f"  • {f}")

    print("\n" + "="*50)

    # 3. Cari dan inspeksi file master data
    search_pattern = os.path.join(FOLDER_PATH, "*master*")
    found = glob.glob(search_pattern)

    if not found:
        # Coba cari alternatif file xlsx/csv lainnya
        found = glob.glob(os.path.join(FOLDER_PATH, "*.xlsx")) + glob.glob(os.path.join(FOLDER_PATH, "*.csv"))

    if found:
        file_target = found[0]
        print(f"📌 File Master Terdeteksi: {os.path.basename(file_target)}")
        print(f"📍 Path Lengkap : {file_target}\n")

        # Read header & kolom
        if file_target.endswith(('.xlsx', '.xls')):
            df_cek = pd.read_excel(file_target, nrows=3)
        else:
            df_cek = pd.read_csv(file_target, nrows=3)

        print("📌 Daftar Kolom yang Ada di File Tersebut:")
        for idx, col in enumerate(df_cek.columns):
            print(f"   [{idx}] '{col}'")
    else:
        print("❌ Tidak ditemukan file .xlsx atau .csv sama sekali di folder tersebut.")

import os
import glob
import pandas as pd
import gensim
from gensim import corpora
from gensim.models import LdaModel, CoherenceModel
from google.colab import drive
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import ComplementNB
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

# 1. KONEKSI GOOGLE DRIVE
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

FOLDER_PATH = '/content/drive/MyDrive/_Skripsi_Vtuber'

# 2. BACA FILE DATASET DARI DRIVE
def load_excel_or_csv(keyword):
    search_pattern = os.path.join(FOLDER_PATH, f"*{keyword}*")
    found = glob.glob(search_pattern)
    if not found:
        raise FileNotFoundError(f"File '{keyword}' tidak ditemukan di {FOLDER_PATH}")
    file_path = found[0]
    print(f"Membaca file: {os.path.basename(file_path)}")
    if file_path.endswith('.xlsx') or file_path.endswith('.xls'):
        df = pd.read_excel(file_path)
    else:
        df = pd.read_csv(file_path)
    df.columns = df.columns.astype(str).str.strip()
    return df

df_latih = load_excel_or_csv('data_latih')
df_master = load_excel_or_csv('master_data')

# FUNGSI DETEKSI KOLOM FLEKSIBEL
def cari_kolom(df, keywords):
    for col in df.columns:
        col_lower = str(col).lower()
        if any(k in col_lower for k in keywords):
            return col
    cols_obj = [c for c in df.columns if df[c].dtype == 'object']
    if cols_obj:
        return cols_obj[0]
    return df.columns[0]

col_teks_latih = cari_kolom(df_latih, ['text', 'teks', 'clean', 'chat', 'pesan', 'comment'])
col_label_latih = cari_kolom(df_latih, ['label', 'sentimen', 'sentiment', 'target', 'kelas'])
col_teks_master = cari_kolom(df_master, ['text', 'teks', 'clean', 'chat', 'pesan', 'comment'])

print(f"-> Kolom Teks Latih  : '{col_teks_latih}'")
print(f"-> Kolom Label Latih : '{col_label_latih}'")
print(f"-> Kolom Teks Master : '{col_teks_master}'\n")

# 3. TRAIN CNB & PREDIKSI SENTIMEN
print("Memproses prediksi sentimen CNB...")
X_train, X_test, y_train, y_test = train_test_split(
    df_latih[col_teks_latih].fillna('').astype(str),
    df_latih[col_label_latih],
    test_size=0.2,
    random_state=42
)
model_cnb = make_pipeline(TfidfVectorizer(), ComplementNB())
model_cnb.fit(X_train, y_train)

df_master['sentimen_prediksi'] = model_cnb.predict(df_master[col_teks_master].fillna('').astype(str))
print("Prediksi sentimen selesai!")
print("Distribusi hasil prediksi:")
print(df_master['sentimen_prediksi'].value_counts())
print("\n")

# 4. FUNGSI ANALISIS LDA FLEKSIBEL
def run_lda(df_subset, label_nama, num_topics=5):
    if len(df_subset) == 0:
        print(f"⚠️ Data untuk {label_nama} kosong, LDA dilewati.\n")
        return

    print("=" * 50)
    print(f"ANALISIS LDA CHAT {label_nama.upper()} ({len(df_subset)} BARIS)")
    print("=" * 50)

    tokens = [str(text).split() for text in df_subset[col_teks_master].fillna('') if str(text).strip()]
    dict_lda = corpora.Dictionary(tokens)
    dict_lda.filter_extremes(no_below=3, no_above=0.5)

    if len(dict_lda) == 0:
        print("⚠️ Kata kunci terlalu sedikit setelah filter, LDA dilewati.\n")
        return

    corpus = [dict_lda.doc2bow(text) for text in tokens]

    lda = LdaModel(corpus=corpus, id2word=dict_lda, num_topics=num_topics, random_state=42, passes=10, alpha='auto')
    coherence = CoherenceModel(model=lda, texts=tokens, dictionary=dict_lda, coherence='c_v')
    score = coherence.get_coherence()

    print(f"Coherence Score (c_v) {label_nama}: {score:.4f}\n")
    for idx, topic in lda.print_topics(num_topics=num_topics, num_words=6):
        print(f"  * Topik #{idx + 1}: {topic}")
    print("\n")

# DETEKSI DAN JALANKAN LDA UNTUK SEMUA UNIK LABEL
label_unik = df_master['sentimen_prediksi'].unique()

for lbl in label_unik:
    df_sub = df_master[df_master['sentimen_prediksi'] == lbl]
    run_lda(df_sub, str(lbl))

# SIMPAN HASIL PREDIKSI KE EXCEL
output_file = os.path.join(FOLDER_PATH, "master_data_vtuber_hasil_prediksi.xlsx")
df_master.to_excel(output_file, index=False)
print(f"✅ File berhasil disimpan di Google Drive:\n{output_file}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import os
# 
# st.set_page_config(page_title="Dashboard Analisis Sentimen VTuber", layout="wide")
# 
# st.title("📊 Dashboard Analisis Sentimen & Topik Chat VTuber")
# 
# # Path file di Google Drive
# FILE_PATH = "/content/drive/MyDrive/_Skripsi_Vtuber/hasil_akhir_analisis_skripsi.xlsx"
# 
# @st.cache_data
# def load_data():
#     if os.path.exists(FILE_PATH):
#         return pd.read_excel(FILE_PATH)
#     # Fallback jika file berada di folder lokal Colab
#     return pd.read_excel("hasil_akhir_analisis_skripsi.xlsx")
# 
# try:
#     df = load_data()
# 
#     # Sidebar Filter
#     st.sidebar.header("Filter Data")
#     vtuber_filter = st.sidebar.multiselect("Pilih VTuber:", options=df['VTuber Name'].unique(), default=df['VTuber Name'].unique())
#     stream_filter = st.sidebar.multiselect("Pilih Stream Type:", options=df['Stream Type'].unique(), default=df['Stream Type'].unique())
# 
#     df_filtered = df[(df['VTuber Name'].isin(vtuber_filter)) & (df['Stream Type'].isin(stream_filter))]
# 
#     # Ringkasan Angka Utama
#     col1, col2, col3 = st.columns(3)
#     col1.metric("Total Chat", f"{len(df_filtered):,}")
#     col2.metric("Sentimen Positif", f"{(df_filtered['Prediksi Sentimen']=='Positif').mean()*100:.1f}%")
#     col3.metric("Sentimen Negatif", f"{(df_filtered['Prediksi Sentimen']=='Negatif').mean()*100:.1f}%")
# 
#     st.markdown("---")
# 
#     # Bagian Chart
#     c1, c2 = st.columns(2)
# 
#     with c1:
#         st.subheader("Distribusi Sentimen per VTuber")
#         fig_sent = px.histogram(df_filtered, x="VTuber Name", color="Prediksi Sentimen", barmode="group")
#         st.plotly_chart(fig_sent, use_container_width=True)
# 
#     with c2:
#         st.subheader("Distribusi Topik Dominan (LDA)")
#         fig_topic = px.pie(df_filtered, names="Topik Dominan", title="Proporsi Topik")
#         st.plotly_chart(fig_topic, use_container_width=True)
# 
#     # Tabel Data
#     st.subheader("Detail Data Chat")
#     st.dataframe(df_filtered[['VTuber Name', 'Chat Text', 'Stream Type', 'Prediksi Sentimen', 'Topik Dominan']])
# 
# except Exception as e:
#     st.error(f"File data tidak ditemukan atau bermasalah: {e}")

from google.colab import drive
import pandas as pd
import glob
import os

print("=== 1. MOUNTING GOOGLE DRIVE ===")
drive.mount('/content/drive', force_remount=True)

print("\n=== 2. MENCARI FILE DATABASE ===")
# Mencari file .xlsx di Google Drive
files = glob.glob('/content/drive/MyDrive/**/*.xlsx', recursive=True)

# Filter file yang relevan dengan skripsi/vtuber
relevant_files = [f for f in files if any(k in os.path.basename(f).lower() for k in ['skripsi', 'master', 'vtuber', 'prediksi', 'hasil'])]

if relevant_files:
    print(f"✅ Ditemukan {len(relevant_files)} file relevan:")
    for i, f in enumerate(relevant_files):
        print(f"   [{i+1}] {f}")

    # Ambil file pertama yang ditemukan
    target_file = relevant_files[0]
    print(f"\n📂 Membaca file: {target_file}")

    df_check = pd.read_excel(target_file)

    print("\n✅ KONEKSI BERHASIL!")
    print(f"📊 Total Baris Data : {len(df_check):,} baris")
    print("📋 Kolom yang Tersedia:")
    for col in df_check.columns:
        print(f"   - {col}")

    # Simpan ke workspace lokal Colab untuk Streamlit
    df_check.to_excel('hasil_akhir_analisis_skripsi.xlsx', index=False)
    print("\n💾 File disalin ke workspace Colab sebagai 'hasil_akhir_analisis_skripsi.xlsx'")

else:
    print("⚠️ File Excel tidak ditemukan otomatis. Pastikan file .xlsx sudah ada di Google Drive kamu.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import os
# 
# # 1. Konfigurasi Halaman
# st.set_page_config(
#     page_title="VTuber Analytics Dashboard",
#     page_icon="🎭",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # 2. Styling UI Modern
# st.markdown("""
#     <style>
#     @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700&display=swap');
# 
#     html, body, [class*="css"] {
#         font-family: 'Plus Jakarta Sans', sans-serif;
#     }
#     .block-container {
#         padding-top: 1.5rem;
#         padding-bottom: 2rem;
#     }
#     .metric-card {
#         background: rgba(255, 255, 255, 0.03);
#         border: 1px solid rgba(255, 255, 255, 0.08);
#         border-radius: 12px;
#         padding: 16px 20px;
#     }
#     .metric-title {
#         font-size: 0.8rem;
#         color: #A0AEC0;
#         font-weight: 600;
#         text-transform: uppercase;
#         letter-spacing: 0.5px;
#     }
#     .metric-value {
#         font-size: 1.8rem;
#         font-weight: 700;
#         color: #FFFFFF;
#     }
#     .metric-sub {
#         font-size: 0.8rem;
#         color: #718096;
#     }
#     .lda-box {
#         background: rgba(99, 102, 241, 0.08);
#         border-left: 4px solid #6366F1;
#         padding: 12px 16px;
#         border-radius: 4px;
#         margin-bottom: 15px;
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# # 3. Load Data
# @st.cache_data
# def load_data():
#     file_name = 'hasil_akhir_analisis_skripsi.xlsx'
#     if not os.path.exists(file_name):
#         raise FileNotFoundError("File database belum disalin.")
#     return pd.read_excel(file_name)
# 
# try:
#     df = load_data()
# except Exception as e:
#     st.error(f"⚠️ Error memuat data: {e}")
#     st.stop()
# 
# # Auto Detect Kolom
# col_vtuber = 'VTuber Name'
# col_stream = 'Stream Type'
# col_sentimen = 'Prediksi Sentimen'
# col_topik_raw = 'Klaster Topik Dominan'
# 
# # Map Nomor Topik LDA ke Label Deskriptif
# TOPIC_MAP = {
#     1: "Topik 1: Sapaan & Interaksi",
#     2: "Topik 2: Respon & Obrolan",
#     3: "Topik 3: Ucapan Datang / Live",
#     4: "Topik 4: Apresiasi Stream (Otsu)",
#     5: "Topik 5: Ekspresi Suka / Tertawa",
#     "1": "Topik 1: Sapaan & Interaksi",
#     "2": "Topik 2: Respon & Obrolan",
#     "3": "Topik 3: Ucapan Datang / Live",
#     "4": "Topik 4: Apresiasi Stream (Otsu)",
#     "5": "Topik 5: Ekspresi Suka / Tertawa"
# }
# 
# # Tambahkan kolom nama topik deskriptif
# col_topik = 'Nama Topik LDA'
# df[col_topik] = df[col_topik_raw].map(TOPIC_MAP).fillna(df[col_topik_raw].astype(str))
# 
# COLOR_POS = "#10B981"
# COLOR_NEG = "#EF4444"
# COLOR_THEME = ["#6366F1", "#8B5CF6", "#EC4899", "#F59E0B", "#3B82F6", "#10B981", "#14B8A6"]
# 
# def style_fig(fig):
#     fig.update_layout(
#         paper_bgcolor="rgba(0,0,0,0)",
#         plot_bgcolor="rgba(0,0,0,0)",
#         font=dict(family="Plus Jakarta Sans", color="#E2E8F0"),
#         margin=dict(l=20, r=20, t=30, b=20),
#         legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
#     )
#     return fig
# 
# # HEADER
# st.title("🎭 VTuber Chat Sentiment & LDA Topic Dashboard")
# st.caption("Eksplorasi Komparatif Sentimen dan Pemodelan Topik LDA Chat VTuber")
# 
# # SIDEBAR GLOBAL FILTER
# st.sidebar.markdown("### 🎛️ Filter Panel Global")
# all_vtubers = sorted(df[col_vtuber].dropna().unique().tolist())
# selected_vtubers = st.sidebar.multiselect("Pilih VTuber", all_vtubers, default=all_vtubers)
# 
# all_streams = sorted(df[col_stream].dropna().unique().tolist())
# selected_streams = st.sidebar.multiselect("Pilih Kategori Stream", all_streams, default=all_streams)
# 
# df_filtered = df[(df[col_vtuber].isin(selected_vtubers)) & (df[col_stream].isin(selected_streams))]
# 
# if df_filtered.empty:
#     st.warning("Data kosong untuk kombinasi filter ini.")
#     st.stop()
# 
# # TAB NAVIGATION
# tab1, tab2, tab3, tab4 = st.tabs([
#     "📊 Ringkasan & Referensi LDA",
#     "👤 Profil & Perbandingan VTuber",
#     "🎮 Analisis Kategori Stream",
#     "📑 Raw Data Chat"
# ])
# 
# # ==========================================
# # TAB 1: RINGKASAN & LDA
# # ==========================================
# with tab1:
#     total_chat = len(df_filtered)
#     pos_chat = (df_filtered[col_sentimen] == 'Positif').sum()
#     neg_chat = (df_filtered[col_sentimen] == 'Negatif').sum()
#     pos_pct = (pos_chat / total_chat * 100) if total_chat > 0 else 0
#     neg_pct = (neg_chat / total_chat * 100) if total_chat > 0 else 0
# 
#     c1, c2, c3 = st.columns(3)
#     c1.markdown(f'<div class="metric-card"><div class="metric-title">Total Chat Menganalisis</div><div class="metric-value">{total_chat:,}</div></div>', unsafe_allow_html=True)
#     c2.markdown(f'<div class="metric-card"><div class="metric-title">Sentimen Positif</div><div class="metric-value" style="color:{COLOR_POS}">{pos_pct:.1f}%</div><div class="metric-sub">{pos_chat:,} chat</div></div>', unsafe_allow_html=True)
#     c3.markdown(f'<div class="metric-card"><div class="metric-title">Sentimen Negatif</div><div class="metric-value" style="color:{COLOR_NEG}">{neg_pct:.1f}%</div><div class="metric-sub">{neg_chat:,} chat</div></div>', unsafe_allow_html=True)
# 
#     st.markdown("<br>", unsafe_allow_html=True)
# 
#     # Keterangan Kata Kunci LDA
#     with st.expander("📖 **Petunjuk Kata Kunci Tiap Topik LDA (Klik untuk Membuka)**", expanded=False):
#         st.markdown("""
#         * **Topik 1 (Sapaan & Interaksi)**: *bang, banget, sil, tris, kalian, malam*
#         * **Topik 2 (Respon & Obrolan)**: *aku, di, itu, ga, yang, ada*
#         * **Topik 3 (Ucapan Datang/Live)**: *the, live, selamat, datang, di, semoga*
#         * **Topik 4 (Apresiasi Stream)**: *kak, halo, jangan, otsu, stream, ka*
#         * **Topik 5 (Ekspresi Suka/Tertawa)**: *lagi, dan, wkwkwk, suka, lah, dengan*
#         """)
# 
#     col_a, col_b = st.columns(2)
#     with col_a:
#         st.markdown("##### Proporsi Sentimen Chat")
#         fig_s = px.pie(df_filtered, names=col_sentimen, color=col_sentimen, color_discrete_map={'Positif': COLOR_POS, 'Negatif': COLOR_NEG}, hole=0.6)
#         st.plotly_chart(style_fig(fig_s), use_container_width=True)
# 
#     with col_b:
#         st.markdown("##### Proporsi Topik LDA Dominan")
#         fig_t = px.pie(df_filtered, names=col_topik, hole=0.6, color_discrete_sequence=COLOR_THEME)
#         st.plotly_chart(style_fig(fig_t), use_container_width=True)
# 
#     st.markdown("---")
#     st.markdown("##### 📌 Tabel Distribusi Frekuensi Topik LDA (Bab IV Skripsi)")
#     topik_df = df_filtered[col_topik].value_counts().reset_index()
#     topik_df.columns = ['Nama Topik LDA', 'Jumlah Chat']
#     topik_df['Persentase (%)'] = (topik_df['Jumlah Chat'] / total_chat * 100).round(2)
#     st.dataframe(topik_df, use_container_width=True)
# 
# # ==========================================
# # TAB 2: PROFIL & PERBANDINGAN VTUBER
# # ==========================================
# with tab2:
#     st.markdown("### 🔍 Filter Individual 1 VTuber")
#     selected_single_vt = st.selectbox("Pilih 1 VTuber untuk melihat analisis detailnya:", all_vtubers)
# 
#     df_single = df[df[col_vtuber] == selected_single_vt]
# 
#     p1, p2, p3 = st.columns(3)
#     with p1:
#         st.markdown(f"##### Kategori Stream ({selected_single_vt})")
#         fig_single_cat = px.pie(df_single, names=col_stream, hole=0.55, color_discrete_sequence=COLOR_THEME)
#         st.plotly_chart(style_fig(fig_single_cat), use_container_width=True)
# 
#     with p2:
#         st.markdown(f"##### Topik LDA Dominan ({selected_single_vt})")
#         fig_single_top = px.pie(df_single, names=col_topik, hole=0.55, color_discrete_sequence=COLOR_THEME)
#         st.plotly_chart(style_fig(fig_single_top), use_container_width=True)
# 
#     with p3:
#         st.markdown(f"##### Sebaran Sentimen ({selected_single_vt})")
#         fig_single_sent = px.pie(df_single, names=col_sentimen, hole=0.55, color_discrete_map={'Positif': COLOR_POS, 'Negatif': COLOR_NEG})
#         st.plotly_chart(style_fig(fig_single_sent), use_container_width=True)
# 
#     st.markdown("---")
#     st.markdown("### 🏆 Diagram Perbandingan Antar VTuber")
# 
#     # Ranking Sentimen
#     vt_stats = df_filtered.groupby([col_vtuber, col_sentimen]).size().unstack(fill_value=0)
#     if 'Positif' not in vt_stats.columns: vt_stats['Positif'] = 0
#     if 'Negatif' not in vt_stats.columns: vt_stats['Negatif'] = 0
#     vt_stats['Total'] = vt_stats['Positif'] + vt_stats['Negatif']
#     vt_stats['Rata_Rata_Positif (%)'] = (vt_stats['Positif'] / vt_stats['Total']) * 100
#     vt_stats = vt_stats.sort_values(by='Rata_Rata_Positif (%)', ascending=True).reset_index()
# 
#     fig_rank = px.bar(
#         vt_stats, y=col_vtuber, x='Rata_Rata_Positif (%)', orientation='h',
#         text_auto='.1f', color='Rata_Rata_Positif (%)', color_continuous_scale='greens',
#         title="Ranking Persentase Sentimen Positif per VTuber"
#     )
#     st.plotly_chart(style_fig(fig_rank), use_container_width=True)
# 
#     col_v1, col_v2 = st.columns(2)
#     with col_v1:
#         st.markdown("##### Sebaran Sentimen per VTuber")
#         fig_vt_sent = px.histogram(df_filtered, x=col_vtuber, color=col_sentimen, barmode='group', color_discrete_map={'Positif': COLOR_POS, 'Negatif': COLOR_NEG})
#         st.plotly_chart(style_fig(fig_vt_sent), use_container_width=True)
# 
#     with col_v2:
#         st.markdown("##### Sebaran Kategori Stream per VTuber")
#         fig_vt_cat = px.histogram(df_filtered, x=col_vtuber, color=col_stream, barmode='stack', color_discrete_sequence=COLOR_THEME)
#         st.plotly_chart(style_fig(fig_vt_cat), use_container_width=True)
# 
#     st.markdown("##### Sebaran Topik LDA per VTuber")
#     fig_vt_lda = px.histogram(df_filtered, x=col_vtuber, color=col_topik, barmode='stack', color_discrete_sequence=COLOR_THEME)
#     st.plotly_chart(style_fig(fig_vt_lda), use_container_width=True)
# 
# # ==========================================
# # TAB 3: KATEGORI STREAM
# # ==========================================
# with tab3:
#     st.markdown("### 🎮 Perbandingan Berdasarkan Kategori Stream")
#     col_k1, col_k2 = st.columns(2)
#     with col_k1:
#         st.markdown("##### Sentimen per Kategori Stream")
#         fig_cat_sent = px.histogram(df_filtered, x=col_stream, color=col_sentimen, barmode='group', color_discrete_map={'Positif': COLOR_POS, 'Negatif': COLOR_NEG})
#         st.plotly_chart(style_fig(fig_cat_sent), use_container_width=True)
# 
#     with col_k2:
#         st.markdown("##### Topik LDA per Kategori Stream")
#         fig_cat_top = px.histogram(df_filtered, x=col_stream, color=col_topik, barmode='stack', color_discrete_sequence=COLOR_THEME)
#         st.plotly_chart(style_fig(fig_cat_top), use_container_width=True)
# 
# # ==========================================
# # TAB 4: RAW DATA
# # ==========================================
# with tab4:
#     st.markdown("### 📑 Raw Data Chat Interaktif")
#     st.dataframe(df_filtered, use_container_width=True)

import time
import os

# 1. Matikan semua proses lama
!pkill -f streamlit
!pkill -f cloudflared

# 2. Pastikan cloudflared ada
if not os.path.exists('/usr/local/bin/cloudflared'):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared
    !chmod +x /usr/local/bin/cloudflared

# 3. Jalankan Streamlit & simpan log ke file streamlit.log
!nohup streamlit run app.py > streamlit.log 2>&1 &

# 4. Jalankan Cloudflare Tunnel
!nohup /usr/local/bin/cloudflared tunnel --url http://localhost:8501 > cloudflare.log 2>&1 &

time.sleep(6)

# 5. Tampilkan status/error dari Streamlit
print("=== LOG STREAMLIT (Cek jika ada error Python) ===")
!cat streamlit.log

print("\n=== LINK DASHBOARD KAMU ===")
!cat cloudflare.log | grep -o 'https://[^"]*trycloudflare.com'

